baseURL = 'https://lanke-hugo.github.io/'
languageCode = 'zh-CN'
title = '烂柯的 Blog'
theme = 'hugo-theme-reimu-blog'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true
[markup.highlight]
guessSyntax = true
noClasses = false